javax.imageio.spi.ServiceRegistry.getServiceProviders.useOrdering=true
org.apache.commons.lang3.math.FractionJPanel.sortFileSuffixes=true
org.apache.commons.lang3.math.FractionJPanel.preferredFileSuffix=png